# Generated by Django 5.2.17 on 2026-09-13 15:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROJECTS',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.TextField()),
                ('category', models.CharField(choices=[('gamedevelopment', 'Game Development'), ('research', 'Research'), ('hardware', 'Hardware'), ('machinelearning', 'Machine Learning'), ('webdevelopment', 'Web Development'), ('mobiledevelopment', 'Mobile Development'), ('videoediting', 'Video Editing'), ('graphicsdesign', 'Graphics Design'), ('other', 'Other')], default='gamedevelopment', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
