# Generated by Django 5.2.17 on 2026-09-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tech_stack',
            field=models.CharField(default='', max_length=255),
        ),
    ]
