# Generated by Django 5.2.17 on 2026-09-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projects_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='category',
        ),
        migrations.AddField(
            model_name='experience',
            name='link',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position',
            field=models.CharField(default='text', max_length=255),
        ),
        migrations.AddField(
            model_name='experience',
            name='skillset',
            field=models.CharField(default='text', max_length=255),
        ),
    ]
